image:
    file: Dockerfile
tasks:
  - init: "echo 'export STACK_ROOT=/workspace/idris-grin/.stack' >> ~/.bashrc; mkdir -p $STACK_ROOT; source ~/.bashrc; echo 'local-bin-path: /workspace/idris-grin/.bin' > $STACK_ROOT/config.yaml; stack install"
