resolver: nightly-2018-11-07

# due to functor-infix
allow-newer: true

packages:
- "."

extra-deps:
  - monad-gen-0.3.0.1
  - functor-infix-0.0.5
  - idris-1.3.1
  - cheapskate-0.1.1.1
  - megaparsec-6.5.0
  - neat-interpolation-0.3.2.2
  - set-extra-1.4.1
  - git: https://github.com/grin-tech/grin
    commit: f25b1be0d34de678ec0d6c0c474d008738d52066
    subdirs:
    - grin
  - git: https://github.com/llvm-hs/llvm-hs-pretty
    commit: 0d04346ea179e96797a284d094e44e538fbddcf2
  - git: https://github.com/csabahruska/llvm-hs.git
    commit: 37aaa694d2f7907634f7af602d9aae125101db8d
    subdirs:
    - llvm-hs

flags:
  llvm-hs:
    shared-llvm: true

build:
  test-arguments:
    additional-args:
      - "--seed=11010"
