resolver: lts-14.16

# due to functor-infix
allow-newer: true

packages:
  - '.'
  # - '../grin/grin'


extra-deps:
  - monad-gen-0.3.0.1
  - functor-infix-0.0.5
  - idris-1.3.2
  - cheapskate-0.1.1.1
  - set-extra-1.4.1
  - llvm-hs-pretty-0.6.1.0

  - github: grin-compiler/grin
    commit: 4c747d1e78196d9d2a303c0454a24c1fbaa13261
    subdirs:
      - grin

  - github: csabahruska/llvm-hs
    commit: 868e23a13942703255979369defdb49ac57b6866
    subdirs:
      - llvm-hs
      - llvm-hs-pure

flags:
  llvm-hs:
    shared-llvm: true

build:
  test-arguments:
    additional-args:
      - "--seed=11010"
