resolver: nightly-2018-11-07

# due to functor-infix
allow-newer: true

packages:
- "."
# - "../grin/grin"

extra-deps:
  - monad-gen-0.3.0.1
  - functor-infix-0.0.5
  - idris-1.3.1
  - cheapskate-0.1.1.1
  - megaparsec-6.5.0
  - neat-interpolation-0.3.2.2
  - set-extra-1.4.1
  - git: https://github.com/grin-tech/grin
    commit: 633de22367b70ab3924fe3b9f560cae50bea6859
    subdirs:
    - grin
  - git: https://github.com/llvm-hs/llvm-hs-pretty
    commit: 0d04346ea179e96797a284d094e44e538fbddcf2
  - git: https://github.com/csabahruska/llvm-hs.git
    commit: 868e23a13942703255979369defdb49ac57b6866
    subdirs:
    - llvm-hs
    - llvm-hs-pure

flags:
  llvm-hs:
    shared-llvm: true

build:
  test-arguments:
    additional-args:
      - "--seed=11010"
